# -*- 构建「内置账号」分发版 -*-
#
# 用法：
#   .\build-friend.ps1                          # 从默认 cookie 文件读取
#   .\build-friend.ps1 -CookieFile "D:\my.txt"   # 指定 cookie 文件
#   .\build-friend.ps1 -Cookie "MUSIC_U=..."     # 直接传入
#   .\build-friend.ps1 -Clean                    # 只清除已生成的内置密钥
#
# 流程：读取 cookie → 生成 Secrets.Local.cs（XOR+Base64 混淆）→ 编译 → 删除该文件
# 注意：生成的 Secrets.Local.cs 已被 .gitignore 排除，绝不会进入公开仓库。

param(
    [string]$CookieFile = "..\liusen_download\.netease_cookie.txt",
    [string]$Cookie = "",
    [string]$OutDir = "dist-friend",
    [switch]$Clean
)

$ErrorActionPreference = "Stop"
$root = $PSScriptRoot
Set-Location $root
$secretPath = Join-Path $root "Secrets.Local.cs"
$key = "MusicDL-2026-obfuscate"

function Remove-Secret {
    if (Test-Path $secretPath) {
        Remove-Item $secretPath -Force
        Write-Host "[清理] 已删除 Secrets.Local.cs" -ForegroundColor Yellow
    }
}

if ($Clean) {
    Remove-Secret
    exit 0
}

# ---------- 1) 取得 cookie ----------
if ([string]::IsNullOrWhiteSpace($Cookie)) {
    $resolved = Resolve-Path -LiteralPath $CookieFile -ErrorAction SilentlyContinue
    if (-not $resolved) {
        Write-Host "找不到 cookie 文件：$CookieFile" -ForegroundColor Red
        Write-Host "请用 -CookieFile 指定路径，或用 -Cookie 直接传入。" -ForegroundColor Red
        exit 1
    }
    $Cookie = (Get-Content -LiteralPath $resolved -Raw).Trim()
}

if ([string]::IsNullOrWhiteSpace($Cookie)) {
    Write-Host "cookie 内容为空。" -ForegroundColor Red
    exit 1
}
if ($Cookie -notmatch 'MUSIC_U=') {
    Write-Host "警告：cookie 中未发现 MUSIC_U=，可能不是有效的网易云登录态。" -ForegroundColor Yellow
}

Write-Host "[1/4] 已读取 cookie（长度 $($Cookie.Length)）"

# ---------- 2) 生成混淆后的 Secrets.Local.cs ----------
$bytes = [System.Text.Encoding]::UTF8.GetBytes($Cookie)
$keyBytes = [System.Text.Encoding]::UTF8.GetBytes($key)
for ($i = 0; $i -lt $bytes.Length; $i++) {
    $bytes[$i] = $bytes[$i] -bxor $keyBytes[$i % $keyBytes.Length]
}
$encoded = [Convert]::ToBase64String($bytes)

$content = @"
// <auto-generated> 由 build-friend.ps1 生成，请勿提交（已在 .gitignore 中排除）。
namespace MusicDownloader;

internal static partial class Secrets
{
    private const string BuiltInCookieEncoded = "$encoded";
}
"@
[System.IO.File]::WriteAllText($secretPath, $content, [System.Text.UTF8Encoding]::new($false))
Write-Host "[2/4] 已生成 Secrets.Local.cs（XOR+Base64 混淆）"

# ---------- 3) 编译 ----------
try {
    Write-Host "[3/4] 开始编译（首次需还原 WebView2 包，可能较慢）..."
    dotnet publish -c Release -o $OutDir
    if ($LASTEXITCODE -ne 0) { throw "dotnet publish 失败（退出码 $LASTEXITCODE）" }

    $exe = Get-ChildItem (Join-Path $root $OutDir) -Filter "*.exe" | Select-Object -First 1
    if (-not $exe) { throw "未找到编译产物" }

    # 重命名：公开版与内置账号版默认同名（都叫「音乐下载器.exe」），
    # 复制分发时极易拿错，这里强制加后缀区分。
    $outDirFull = Join-Path $root $OutDir
    $finalPath = Join-Path $outDirFull "音乐下载器-已内置账号.exe"
    if ($exe.FullName -ne $finalPath) {
        Move-Item -LiteralPath $exe.FullName -Destination $finalPath -Force
    }
    Get-ChildItem $outDirFull -Filter "*.exe" |
        Where-Object { $_.Name -ne "音乐下载器-已内置账号.exe" } |
        Remove-Item -Force -ErrorAction SilentlyContinue

    $final = Get-Item -LiteralPath $finalPath
    $sizeMb = [math]::Round($final.Length / 1MB, 2)
    Write-Host "[4/4] 完成：$($final.FullName) ($sizeMb MB)" -ForegroundColor Green
    Write-Host ""
    Write-Host "  文件名带「已内置账号」后缀，勿与公开版混淆。" -ForegroundColor Cyan
    Write-Host "提示：该 exe 内含登录态，请仅私下分享给信任的人。" -ForegroundColor Yellow
    Write-Host "      若怀疑外泄，可在网易云「设置 → 退出所有设备」使凭证失效。" -ForegroundColor Yellow
}
finally {
    # 无论成功与否都清除明文来源，避免残留
    Remove-Secret
}
